### ISSUE TITLE
netlink: 'xxxxxx': attribute type 1 has an invalid length.

### ISSUE THREAD

**Issue by liyakuniot** [bmegli/wifi-scan#25] opened 2019-12-31 02:56 UTC
I don't know how this problem is caused.if you can fix this,please tell me.thanks!

**Comment by bmegli** [comment] 2019-12-31 08:35
Hi @lliyakun,

I need more details:
- what is 'xxxxxx'
- what OS are you on
- what are you doing

**Comment by bmegli** [comment] 2019-12-31 08:52
Ok,

Guessing the missing details:
-  `xxxxxx` is like `'wifi-scan-stati'`
- the message comes in dmesg (something you should point out)
- you are calling `wifi-scan-station`

The message comes from Linux kernel, [exactly this](https://github.com/torvalds/linux/blob/80f232121b69cc69a31ccb2b38c1665d770b0710/lib/nlattr.c#L178) line and means that we probably have mismatch on some netlink attribute lenght.

This needs further investigation.

**Comment by bmegli** [comment] 2019-12-31 09:05
Attribute type 1 is NLA_U8 [in the linux kernel](https://github.com/torvalds/linux/blob/06821504fd47a5e5b641aeeb638a0ae10a216ef8/include/net/netlink.h#L167)

This may mean that we are encoding incorrect integer type for some attribute.

**Comment by bmegli** [comment] 2019-12-31 09:27
The message comes only once per run which suggests it's during initialization

**Comment by bmegli** [comment] 2019-12-31 09:28
After double checking the attributes there seems to be mismatch for `CTRL_ATTR_FAMILY_ID`

**Comment by bmegli** [comment] 2019-12-31 09:33
This should be fixed now.

Could you confirm that the problem is fixed for you?

**Comment by liyakuniot** [comment] 2019-12-31 10:22
I tried again,it looks normal，thanks for your reply.：）

**Comment by bmegli** [comment] 2019-12-31 10:51
Thanks for pointing it out!

Kind regards

**Closed as completed by bmegli** 2019-12-31 10:51 UTC
Labels: bug
